/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SampleGradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String a[]){
    	System.out.println("library");
    }
}
